### PR TITLE
Merge Image_Function and Image_Function_Simd

### PR DESCRIPTION
**Pull request by 0x72D0**
PR for #310 

I have some error with the unit_test, every call to simd function fail...

I still have to refactor the performance_test code

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @0x72D0 , thanks for your efforts. I'd definitely have a look this week but it would take some time as there are big changes in the code :)

**Comment by ihhub** [comment]
What we need is to modify existing code for CPU: we don't need to have verification and variable calculation code in each function. We should pass all needed already calculated parameters from common function which now calls SIMD functions.

**Comment by 0x72D0** [comment]
ok I understand, but before changing this we should find why the SIMD code is not working in this version. Also how I should rename the simd namespace (since it's now contains all the common function)?

**Comment by ihhub** [comment]
Hi @0x72D0 , thanks a lot for efforts. I'll take a deep look into it on my weekends as currently I'm extremely busy :(

**Comment by 0x72D0** [comment]
@ihhub no problem :)

**Comment by ihhub** [comment]
Hi @0x72D0 please check code from line 2270 in `src/image_function.cpp` :)

**Comment by 0x72D0** [comment]
@ihhub thanks for spotting this :)

**Comment by ihhub** [comment]
Hi @0x72D0 should we hold this changes for a while? There are not critical of course but they take a lot of time.

**Comment by 0x72D0** [comment]
Yeah, right now I'm stuck on why all the SIMD function unit_test don't work... I agree with the fact that these changes are not critical. So if you think we better hold on them, I'm with you on this!

**Comment by ihhub** [comment]
We're closing this pull request for now as it takes a big redesign.

**Pull request closed without merging**
