### PR TITLE
ConvertTo16Bit() SSE implementation

### PR DESCRIPTION
**Pull request by 0x72D0**
relates to #431

### CODE REVIEW

**Comment by ihhub** [comment]
I'll commit needed changes today.

**Comment by ihhub** [comment]
Hi @0x72D0 , please update the source code from master branch.

**Comment by 0x72D0** [comment]
Hi @ihhub it work on my side:

image

**Comment by ihhub** [comment]
@0x72D0 good job! I'll merge after compilation completion.

**Comment by ihhub** [comment]
@0x72D0 thanks a lot for implementation! Looking forward for another part ;)

**Pull request merged**
