### PR TITLE
Add unit tests for FFT

### PR DESCRIPTION
**Pull request by ihhub**
Added unit tests for FFT CPU based classes.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi, @yannlabou I think the option [`/WX`](https://msdn.microsoft.com/en-us/library/ms235592.aspx) for VIsual Studio projects is wrong. It causes compilation error.

**Comment by yannlabou** [comment]
> Hi, @yannlabou I think the option [`/WX`](https://msdn.microsoft.com/en-us/library/ms235592.aspx) for VIsual Studio projects is wrong. It causes compilation error.

Why? There is nothing inherently bad in treating linker warnings as errors. Do you have a build log for me?

**Comment by ihhub** [comment]
Check [this log](https://ci.appveyor.com/project/ihhub/penguinv/builds/19907718/job/klstu3u6epp7ovym). It was a simple casting warning. I fixed it by explicitly add casting. Let's monitor for another build if any new code would cause the problem again.

**Comment by ihhub** [comment]
Line 226 was `twidx += fstride * k;` which is totally fine and it doesn't relate to linker.

**Pull request merged**
