### PR TITLE
Issue 497: Add Windows Build in Travis

### PR DESCRIPTION
**Pull request by yannlabou**
relates to #497

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @yannlabou . My big apology that it took so much time for review. Everything looks good but I'm thinking that right now we already have Windows build on AppVeyor why don't we try to make a daily/weekly run only for Windows in Travis? I can make daily cron job for this according to [this manual](https://docs.travis-ci.com/user/cron-jobs/). What do you think?

**Comment by ihhub** [comment]
I think we need to separate Windows and Unix builds into AppVeyor and Travis to have as many as possible parallel jobs. We recently added ARM build job as well. Travis supports only 3 parallel jobs. AppVeyor supports no parallel jobs. In total, we could have maximum 4 parallel jobs. My concern is that we reduce number of parallel jobs from 4 to 3.

I'll soon be adding Daily cron jobs so that we could add Windows job into daily.

**Comment by ihhub** [comment]
Hi @yannlabou could we please integrate this changes into cron job ( `if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then` )?

**Comment by yannlabou** [comment]
> Hi @yannlabou could we please integrate this changes into cron job ( `if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then` )?

I might need additional information here. What cron job? And what shall we do if it's a cron job? The changes here added the `Windows` platform to Travis as far as I can remember.

**Comment by ihhub** [comment]
Cron job is a daily run at fixed time of Travis-CI. It is scheduled job in another words. I created it few days ago based on [this manual](https://docs.travis-ci.com/user/cron-jobs/). You can take a look for example at [this run](https://travis-ci.org/ihhub/penguinV/builds/612829261).

My idea is to run Windows job within scheduled run only. I still haven't received a permission from AppVeyor to create scheduled jobs so we can do this in Travis-CI. Recently, I changed the number of iterations for unit tests to 100 to speed up jobs. In cron/scehduled job I set test run as 1000.

**Comment by ihhub** [comment]
On top of this two weeks ago I added ARM build as well which increased build time. I want to reduce build time as I have 2 projects on my account as builds sometimes queuing to be executed which is a bad sign for contributors as they need to wait a long time to get an error message if their changes are wrong.

**Comment by yannlabou** [comment]
> Cron job is a daily run at fixed time of Travis-CI. It is scheduled job in another words. I created it few days ago based on [this manual](https://docs.travis-ci.com/user/cron-jobs/). You can take a look for example at [this run](https://travis-ci.org/ihhub/penguinV/builds/612829261).
> 
> My idea is to run Windows job within scheduled run only. I still haven't received a permission from AppVeyor to create scheduled jobs so we can do this in Travis-CI. Recently, I changed the number of iterations for unit tests to 100 to speed up jobs. In cron/scehduled job I set test run as 1000.

I know what cron jobs are. I wasn't aware that you are already running one for the project. Isn't easier to configure the cron job only for the Windows builds?

**Comment by ihhub** [comment]
> > Cron job is a daily run at fixed time of Travis-CI. It is scheduled job in another words. I created it few days ago based on [this manual](https://docs.travis-ci.com/user/cron-jobs/). You can take a look for example at [this run](https://travis-ci.org/ihhub/penguinV/builds/612829261).
> > My idea is to run Windows job within scheduled run only. I still haven't received a permission from AppVeyor to create scheduled jobs so we can do this in Travis-CI. Recently, I changed the number of iterations for unit tests to 100 to speed up jobs. In cron/scehduled job I set test run as 1000.
> 
> I know what cron jobs are. I wasn't aware that you are already running one for the project. Isn't easier to configure the cron job only for the Windows builds?

This is a tricky part: I want to run Windows only on cron job and to run other platforms as well but with higher amount of unit test runs. Currently only second part is done.

**Comment by ihhub** [comment]
@yannlabou thanks a lot for your contribution to the project! I made changes to run Windows only on cron job. Let's see how it goes on today's cron job.

**Pull request merged**
