### PR TITLE
Simplify unit test cmake file with environment variable support

### PR DESCRIPTION
**Pull request by ihhub**
We use an environment variable to set an input command line parameter for compiled `unit_tests` application. We set iteration count on unit tests to _500_ for **AppVeyor**.

Relates to #241

### CODE REVIEW

**Comment by yannlabou** [comment]
@ihhub Could you please trigger an appveyor build for this pr?

**Comment by ihhub** [comment]
AppVeyor is built for previous commits. AppVeyor has ignore file list to do not build for every change. Please check the history of builds. I triggered rebuild of latest build.

**Comment by ihhub** [comment]
@yannlabou do you have any more comments? We would need to revise these 3 and 2 magic number later :)

**Comment by yannlabou** [comment]
> @yannlabou do you have any more comments? We would need to revise these 3 and 2 magic number later :)

I didn’t manage Travis to get `cat "${TRAVIS_BUILD_DIR}/build/Testing/Temporary/MemoryChecker.*.log"` working :(

**Pull request merged**
