### PR TITLE
Travis CI must fail on build failure

### PR DESCRIPTION
**Pull request by yannlabou**

### CODE REVIEW

**Comment by ihhub** [comment]
@yannlabou , I have an idea: what if we move back the logic from `script/travis/run_script.sh` file into `.travis`. I see in your [another pull request](https://github.com/ihhub/penguinV/pull/200/files) that actually we **can** use environmental variable within `.travis` file. If we move back everything then we don't need to have `pipeline` fix. What do you think?

**Comment by ihhub** [comment]
Oh, now we have the same changes in both pull request. Could you please create a separate branch for this issue from the master branch of the project then you would have 2 separate copies to work on?

**Comment by yannlabou** [comment]
I think I merged the two issue-branches inadvertently. :(

**Comment by ihhub** [comment]
That's okay :) No blame on you.

**Pull request closed without merging**
