### PR TITLE
[CUDA] ProjectionProfile unit test

### PR DESCRIPTION
**Pull request by josephnicholas**
### Changes:
- Added 4 unit tests for ProjectionProfile.

Reference: https://github.com/ihhub/penguinV/issues/579

### CODE REVIEW

**Comment by josephnicholas** [comment]
@ihhub for your review. Thank you.

**Comment by ihhub** [comment]
Hi @josephnicholas I've changed `std::all_of` to `std::any_of` as it should fail if any element of array returns false.

**Comment by josephnicholas** [comment]
> Hi @josephnicholas I've changed `std::all_of` to `std::any_of` as it should fail if any element of array returns false.

Noted on this. I tried to debug it yesterday and assumed that the computed value is always the same as the one in projection. Thanks

**Comment by ihhub** [comment]
@josephnicholas could you please run the tests on your machine to make sure that they are passed?

**Comment by josephnicholas** [comment]
> @josephnicholas could you please run the tests on your machine to make sure that they are passed?

@ihhub Yes I definitely can, but I have to do it after 17:00 GMT +8, since I am currently on macOS that doesn't have CUDA enabled GPU. I will post the results here after.

**Comment by ihhub** [comment]
Great! Let's wait for results. Sadly, our compilation servers don't have GPUs to test :(

**Comment by josephnicholas** [comment]
@ihhub all test passed! :100: 

```[29/40] image_function_cuda::ProjectionProfileForm1Test... OK
[30/40] image_function_cuda::ProjectionProfileForm2Test... OK
[31/40] image_function_cuda::ProjectionProfileForm3Test... OK
[32/40] image_function_cuda::ProjectionProfileForm4Test... OK
[33/40] image_function_cuda::SetPixelForm1Test... OK
[34/40] image_function_cuda::SetPixelForm2Test... OK
[35/40] image_function_cuda::SubtractForm1Test... OK
[36/40] image_function_cuda::SubtractForm2Test... OK
[37/40] image_function_cuda::ThresholdForm1Test... OK
[38/40] image_function_cuda::ThresholdForm2Test... OK
[39/40] image_function_cuda::ThresholdDoubleForm1Test... OK
[40/40] image_function_cuda::ThresholdDoubleForm2Test... OK
40 of 40 tests passed.
```

**Comment by ihhub** [comment]
@josephnicholas thank you very much for your continuous contribution to the project!

**Pull request merged**
