### PR TITLE
add avx support for the accumulate function

### PR DESCRIPTION
**Pull request by 0x72D0**
PR for #113. I add the avx support for the accumulate function, the only thing I found weird in my implementation is it seems to be slower on larger dataset:

screenshot_20181021_224430

I should implement the sse support in the following days.

### CODE REVIEW

**Comment by ihhub** [comment]
Please test the code after my corrections. Regarding the performance tests: your code is slightly faster than CPU first of all and with my tiny changes it should be even faster. Please remember that compiler `could` use SIMD optimizations as well leading to almost identical code.

**Comment by 0x72D0** [comment]
wait there's something I don't understand... The reason why I put the dst_const variable is because without it the loadu function give me a segfault... so why there's is no segfault now even if you pass a non const variable to loadu?

**Comment by ihhub** [comment]
`segfault` could happen because of reading a data which is out of bound for example. Passing a `non-const` argument to a function which requires a `const` argument automatically makes the argument `const`. Please verify on unit tests that everything works fine. If yes we could merge the code :)

**Comment by 0x72D0** [comment]
yes everythings work fine on my side

**Comment by ihhub** [comment]
@0x72D0, thanks a lot again for your work for the project and I hope that you would continue your contribution!

**Comment by ihhub** [comment]
There was a bug in the code which I fixed in [this commit](https://github.com/ihhub/penguinV/commit/d5a9ca02c467fdf1533269f639a9f96b3c7416fa)

**Comment by 0x72D0** [comment]
what was the bug exactly?

**Comment by ihhub** [comment]
`outY` which is a pointer to `result` vector was incremented by `rowSize` (instead of `width`) which is bigger than `width` for situations of ROI (not full) image processing. That's why **form2** of the test had **segfault** (out of bounds).

**Comment by 0x72D0** [comment]
oh! okay I see, thanks for the precision :)

**Pull request merged**
