### PR TITLE
Add OpenCL check in CMake and add cmake files for unit tests

### PR DESCRIPTION
**Pull request by yannlabou**
Adding CMake config for test/unit_tests/opencl

### CODE REVIEW

**Comment by ihhub** [comment]
@yannlabou , I restarted tests on Travis-CI after the fix for AVX failure in master branch. The compilation on **Linux** fails because the script couldn't find `OpenCL` module/directory. There are 2 ways to fix it:
1. Do not compile (and execute) OpenCL unit tests if OpenCL module is not found.
2. Try to find CUDA module and then use OpenCL code there. CUDA usually ships with OpenCL module.

**Comment by yannlabou** [comment]
I will push a mix of option 1 and 2.

**Comment by ihhub** [comment]
I fixed OpenCL compilation on Linux so Travis-CI does not fail anymore. I need some time to figure out why AppVeyor (Windows) fails.

**Comment by ihhub** [comment]
**Appveyor** fails to raised exception in OpeCL unit tests. Could you please modify `main` function of `penguinV/test/unit_tests/opencl/unit_tests_opencl.cpp` file?

```
int main()
{
    try
    {
    ... existing code shifted by 4 pixels to right
    }
    catch( const imageException & ex ) {
        std::cout << "Exception " << ex.what() << " raised during OpenCL unit tests." << std::endl;
        return 0;
    }
    catch( ... ) {
        std::cout << "Unknown exception raised during OpeCL unit tests." << std::endl;
        return 0;
    }
```

You could refer to `penguinV/examples/bitmap_operation/example_bitmap_operation.cpp` file to understand what I mean.
This approach might help to fix OpenCL run failure and identify the source of failure as well.

**Comment by yannlabou** [comment]
@ihhub Thank you! What was the issue on Linux? I can't see the build log. I will take care of  `penguinV/test/unit_tests/opencl/unit_tests_opencl.cpp` later today.

**Comment by ihhub** [comment]
`#include <memory>` was missing which by default on Linux leads to compilation failure for `std::shared_ptr` while for Windows and MacOS it was fine.

**Comment by yannlabou** [comment]
Sure. `std::shared` is defined in `memory` header. I'm wondering why my clang on OS X was happy with that. Thank you anyway :).

**Comment by ihhub** [comment]
I changed the description of the issue and pull request and we don't have performance tests for OpenCL. I will create another issue for performance tests CMake file when tests would be ready.

**Comment by ihhub** [comment]
No luck in exception handling. The change didn't fix the issue. 2 ways to solve it:
1. do not run OpenCL tests on Windows
2. Copy (which one) OpenCL dll to the directory where we create ***.exe** file. Not sure how to find our which file, need to dig the Internet for this :(

**Comment by yannlabou** [comment]
> No luck in exception handling. The change didn't fix the issue. 2 ways to solve it:
> 
> 1. do not run OpenCL tests on Windows
It's doable
> 2. Copy (which one) OpenCL dll to the directory where we create ***.exe** file. Not sure how to find our which file, need to dig the Internet for this :(
If you're 100% sure that the exception is caused by some missing OpenCL DLLs, I can add an [CMake install](https://cmake.org/cmake/help/v3.9/command/install.html#installing-files) directive for the unit_tests_opencl target.

**Comment by ihhub** [comment]
@yannlabou , thanks a lot for your continuous contribution to the project!

**Pull request merged**
