### PR TITLE
Fix makefile for "file_operation" example

### LINKED ISSUE #510: Fix makefile for "file operation" example
We have makefile which locates in `examples/file_operation` directory. Compilation fails when OS doesn't have installed **lpng** library. We must not fail compilation in such case as it's not user friendly. We could output a warning of missing library only.

### PR DESCRIPTION
**Pull request by fullset**
@ihhub could you look, please?

This fix seems strange as for me, but works on my computer.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @fullset , I'll run the code with this check in a while as right now I don't have Linux machine. Give me please maximum 2 days.

**Comment by fullset** [comment]
@ihhub, Sure

**Comment by fullset** [comment]
@ihhub also if you approve this fix, I can apply it to #509 if you would like.

**Comment by ihhub** [comment]
Hi @fullset , the original issue relates to a situation when there is no libpng file so these changes don't fix the issue.

**Comment by fullset** [comment]
Sorry, then I don't understand the problem.

What I have:
1) before my changes:
```
$ sudo apt remove libpng-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libpng-dev' is not installed, so not removed
```
``libpng-dev`` has been already removed.
Then let's try to ``make``.
```
$ make example_file_operation
g++ -std=c++11 -Wall -Wextra -Wstrict-aliasing -Wpedantic -Wconversion -O2 -march=native -D PENGUINV_ENABLED_PNG_SUPPORT -o example_file_operation example_file_operation.cpp ../../src/image_function_helper.cpp ../../src/image_function.cpp ../../src/file/file_image.cpp ../../src/file/bmp_image.cpp ../../src/file/jpeg_image.cpp ../../src/file/png_image.cpp -lpng
../../src/file/png_image.cpp:35:10: fatal error: png.h: No such file or directory
 #include <png.h>
          ^~~~~~~
compilation terminated.
makefile:33: recipe for target 'example_file_operation' failed
make: *** [example_file_operation] Error 1
```
That's what I thought was in issue.

2) after changes:
```
make example_file_operation 

Note! libpng-dev is missing from your computer,
so .png images are not supported.

You can install libpng-dev by:
sudo apt install libpng-dev

g++ -std=c++11 -Wall -Wextra -Wstrict-aliasing -Wpedantic -Wconversion -O2 -march=native -o example_file_operation example_file_operation.cpp ../../src/image_function_helper.cpp ../../src/image_function.cpp ../../src/file/file_image.cpp ../../src/file/bmp_image.cpp ../../src/file/jpeg_image.cpp ../../src/file/png_image.cpp
```
Compilation is successful but without png support.
Ok, let's install ``libpng-dev`` : 
```$ sudo apt install libpng-dev```
and ``make``:
```
$ make example_file_operation 

g++ -std=c++11 -Wall -Wextra -Wstrict-aliasing -Wpedantic -Wconversion -O2 -march=native -D PENGUINV_ENABLED_PNG_SUPPORT -o example_file_operation example_file_operation.cpp ../../src/image_function_helper.cpp ../../src/image_function.cpp ../../src/file/file_image.cpp ../../src/file/bmp_image.cpp ../../src/file/jpeg_image.cpp ../../src/file/png_image.cpp -lpng -lz
```
And it looks like all is OK.

Did you mean some another problem?

**Comment by ihhub** [comment]
Hi @fullset , what I mean is that I have this output:
```
Note! libpng-dev is missing from your computer,
so .png images are not supported.

You can install libpng-dev by:
sudo apt install libpng-dev
```

but no application is created.
I'm on MacOS.

**Comment by fullset** [comment]
Hello @ihhub 
Hmm, the only reason I could imagine why you get this output and there is no application and there are no other errors is that there is no target "all" in makefile. So I've added it.

**Comment by ihhub** [comment]
@fullset , it works now! Thanks! Let's make some code cleanup and I would like to have some clarifications :)

**Comment by fullset** [comment]
>  Let's make some code cleanup 

@ihhub, what kind of cleanup?

**Comment by ihhub** [comment]
I made 2 comments in the code :)

**Comment by ihhub** [comment]
@fullset thanks a lot for your continuous support of the project!

**Pull request merged**
