### PR TITLE
Rename PenguinV_Image into penguinV

### PR DESCRIPTION
**Pull request by ihhub**
relates to #566  and #543

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @fullset, I made the same pull request based on latest code. Let's see how the compilation goes on these changes.

**Comment by ihhub** [comment]
@fullset compilation is passed with no errors (ignore static and dynamic analysis).

**Comment by fullset** [comment]
Hello, @ihhub.

Good news. It's obviously step forward. I guess we can close my old PR.

**Comment by ihhub** [comment]
Cool. Let me fix all code style issues and I merge his pull request then :)

**Pull request merged**
