### PR TITLE
Add median 1D filter to edge detection algorithm

### PR DESCRIPTION
**Pull request by vrozin**
Refers to #346.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @vrozin I modified your function. We cannot use circular filtering as we might have a big difference in values on two edges. Do my changes make sense? I haven't tested them as I modified the file in web editor.

**Comment by ihhub** [comment]
@vrozin could you please then add enumeration for filters and extra step to call this new function? :)

**Comment by vrozin** [comment]
Yes, understood :)

Will add enumeration and the call for median filter.
Would you want me to combine it with Gaussian at this point?

**Comment by ihhub** [comment]
Le'ts add Gaussian later in a separate pull request after committing mean filter first.

**Comment by ihhub** [comment]
Hi @vrozin , I removed ^M at the end of each line. Could you please synchronize your code with master branch?

**Comment by vrozin** [comment]
Ok, got it. 
Yes, I try to always update my branches before pushing changes :)

**Comment by ihhub** [comment]
Hi @vrozin would you mind to make changes if you have spare time for this?

**Comment by vrozin** [comment]
Hi @ihhub, sorry about the delay.
Yes, absolutely. I'll be free on Monday (the holiday), so I'll be able to work on it.

**Comment by vrozin** [comment]
Hi @ihhub! I hope you are doing well :)
I added the enum structure (in `EdgeParameter`) and call for median filter (in `applyFiltering()`), also modified the proposed changes for `meanFilter()` so it seems to be working now.

Please feel free to request changes and I will try to get to them asap.
Sorry about the previous delay.

**Comment by ihhub** [comment]
Hi @vrozin did you update to latest version? It looks like the problem with ^M is still present in your code.

**Comment by vrozin** [comment]
Hmm, I did update it... Ok, let me do it once again when I get home.
Maybe it's the problem with some of the settings in Visual Studio line endings, but this problem should have been fixed already...

**Comment by ihhub** [comment]
Hi @vrozin, source file still remains fully changed.

**Comment by ihhub** [comment]
Closing this pull request as it hasn't been touched for a very long time.

**Pull request closed without merging**
