### PR TITLE
Makefile for CUDA performance tests (WIP #144)

### PR DESCRIPTION
**Pull request by fullset**
Hello, @ihhub.
It was a bit difficult to find time to solve this issue sorry for this.

I've made this makefile but have no possibility to check it. So, Could you look?

### CODE REVIEW

**Comment by ihhub** [comment]
I restarted AppVeyor. It had some error unrelated to your commit.

**Comment by ihhub** [comment]
Let me think about how to check the change. I might modify your branch to be able to run makefile in Travis-CI and then revert back the change.

**Comment by ihhub** [comment]
It works perfectly.

**Comment by ihhub** [comment]
@fullset thank you very much for your continuous contribution to the project!

Would you mind to become a collaborator of the project?

**Comment by fullset** [comment]
@ihhub It would be great.
But what it will mean for me? How it will change my work?

**Comment by ihhub** [comment]
@fullset you would able to manage labels, review pull requests and have a fancy title of owner of the project :)

**Comment by ihhub** [comment]
In other words it doesn't change anything for you but it's as appreciation of your work.

**Pull request merged**
