### PR TITLE
Create base_types.h

### PR DESCRIPTION
**Pull request by ReshmaPD**
create a new file to merge two files containing common code
implement for issue #397

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @ReshmaPD thank you for your efforts but we need more than just add an empty file to fix #397 issue. Could you please implement it?

**Comment by ReshmaPD** [comment]
I was confused about this, I should have clarified it first.
Regarding the issue about comparing the common code and creating a new file, can you please elaborate about how should I approach that? Take the common code from both and implement that in a new file? I am a total beginner and would love to try.

**Comment by ihhub** [comment]
You're correct. We need to create a common classes for both files.

Please put new base classes under `namespace gpu` in your newly created file. These new classes must be templates.
The biggest problem is that OpenCL implementation doesn't allow copy constructor (it's private). Don't worry if you don't have CUDA or OpenCL compilation. Our remote servers (Travis-CI and AppVeyor) do all needed compilation. Plus you can add as many commits as you need to archive the goal. We will still merge all commits into one :)

If you have any questions regarding the implementation please ask. We could discuss even on half made code if you put it for this pull request.

**Comment by ihhub** [comment]
@ReshmaPD if you are not really familiar with templates (which is fine) I could suggest to try to fix another issue like [this](https://github.com/ihhub/penguinV/issues/366) or [this](https://github.com/ihhub/penguinV/issues/373). These issues are pretty straightforward :)

**Comment by ihhub** [comment]
Hi @ReshmaPD how is the progress?

**Comment by ihhub** [comment]
I'm closing this pull request for now as there are no changes in the code.

**Pull request closed without merging**
