### PR TITLE
Bugfixing cppclean output using grep

### PR DESCRIPTION
**Pull request by yannlabou**

### CODE REVIEW

**Comment by ihhub** [comment]
`grep` thinks EXCLUDE_PATTERN_1, 2, 3 are not strings.

**Comment by yannlabou** [comment]
> `grep` thinks EXCLUDE_PATTERN_1, 2, 3 are not strings.

But it works on my Mac :). There might be no need to escape `#`.

**Comment by yannlabou** [comment]
Can you cancel the current builds before I push?

**Comment by ihhub** [comment]
Done.

**Comment by yannlabou** [comment]
Expected [log.txt](https://github.com/ihhub/penguinV/files/2532821/log.txt) vs [log_grep.txt](https://github.com/ihhub/penguinV/files/2532820/log_grep.txt) on current `master`.

**Comment by yannlabou** [comment]
It works! https://travis-ci.org/ihhub/penguinV/jobs/448693224

**Comment by ihhub** [comment]
@yannlabou Thanks a lot for your continious fixes!

**Comment by yannlabou** [comment]
> @yannlabou Thanks a lot for your continious fixes!

Sure. I learnt a lot of Travis and Appveyor these days. I should push some `C++` stuff  some day. ;)

**Comment by ihhub** [comment]
Well, there are a couple of not fixed issues which you would have an interest :) The highest priority is to implement valgrind to find a source of crash

**Pull request merged**
