### PR TITLE
NEON implementation of RgbToBgr() function

### PR DESCRIPTION
**Pull request by 0x72D0**
PR for #117 
here's the performance test:

screenshot_20190113_125414

### CODE REVIEW

**Comment by 0x72D0** [comment]
it's seems like there's an error with the installation of qt in the macOs travis CI

**Comment by ihhub** [comment]
I've restarted the build for MacOS.

**Comment by ihhub** [comment]
@0x72D0 great job as usual! Looking forward for AVX implementation. Do you still need some discussion about AVX?

**Comment by 0x72D0** [comment]
yes I still didn't found an algorithm for AVX

**Pull request merged**
