### PR TITLE
implement ConvertTo16Bit function for neon

### PR DESCRIPTION
**Pull request by 0x72D0**
PR for #431 

I implemented the ConvertTo16Bit function for neon. All unit tests passed:

image

### CODE REVIEW

**Comment by ihhub** [comment]
@0x72D0 could you please update your code with my changes and run tests again? You forgot to remove an extra condition so your new code was not executed.

**Comment by 0x72D0** [comment]
oh yeah I completely forgot this condition :)

**Comment by 0x72D0** [comment]
@ihhub it should be good now, the unit tests pass with the condition

**Comment by ihhub** [comment]
@0x72D0 thank you very much for your contribution!

**Pull request merged**
