### PR TITLE
Issue #179:  modify unit tests for bitmap operation

### PR DESCRIPTION
**Pull request by lrm25**

### CODE REVIEW

**Comment by ihhub** [comment]
I have to check why RGB image tests fails.

**Comment by lrm25** [comment]
Just saw the AppVeyor message, and looked more closely at the image on my machine.  It isn't being saved properly.  Hang on.

**Comment by lrm25** [comment]
In fact, there's no random RGB image generator in the unit test helper.  I can add that too.

**Comment by ihhub** [comment]
@lrm25 , thank you very much for your contribution to the project!

**Pull request merged**
