### PR TITLE
Add base OpenCL types support

### PR DESCRIPTION
**Pull request by ihhub**
relates to #100

### CODE REVIEW

**Comment by ihhub** [comment]
@yannlabou here is a good example of static analysis to be corrected. First thing what I see is that there is no indentation in namespace (proposed solution has no 4 whitespaces shift).

**Comment by yannlabou** [comment]
> @yannlabou here is a good example of static analysis to be corrected. First thing what I see is that there is no indentation in namespace (proposed solution has no 4 whitespaces shift).

I think `NamespaceIndentation: All` is what you need.

**Comment by ihhub** [comment]
Yeah, done this and some other changes as well :) Thanks!

**Comment by yannlabou** [comment]
> Yeah, done this and some other changes as well :) Thanks!

I think we should mention clang-format in [CONTRIBUTING.md](https://github.com/ihhub/penguinV/blob/master/CONTRIBUTING.md).

**Comment by ihhub** [comment]
Moreover, I'm thinking that we could remove [code style](https://github.com/ihhub/penguinV/wiki/Code-Style) page and just mention to refer to this file. From another side not many people would read and understand `clang-format` file.

**Comment by yannlabou** [comment]
> Moreover, I'm thinking that we could remove [code style](https://github.com/ihhub/penguinV/wiki/Code-Style) page and just mention to refer to this file. From another side not many people would read and understand `clang-format` file.

Yes. The page is not needed anymore. Contributors don’t need to read or understand .clang-format (although it’s really self explanatory). They need to run the tool before submitting a pull request. Many editors have support for it. The hardcore vim users probably know clang ;).

**Comment by ihhub** [comment]
> > Moreover, I'm thinking that we could remove [code style](https://github.com/ihhub/penguinV/wiki/Code-Style) page and just mention to refer to this file. From another side not many people would read and understand `clang-format` file.
> 
> Yes. The page is not needed anymore. Contributors don’t need to read or understand .clang-format (although it’s really self explanatory). They need to run the tool before submitting a pull request. Many editors have support for it. The hardcore vim users probably know clang ;).
My worry is not for hardcore users but for beginners. Let's just mention about it as we always can change the code within pull request (or ask a person to do such).

**Comment by ihhub** [comment]
After all coding style is just a recommendation, not a set of strict rules which we must force to follow :) Even if there is some differences in style we shouldn't make a big accent on it as such act pushes developers away.

**Pull request merged**
