### PR TITLE
Adding RgbToRgb functions

### PR DESCRIPTION
**Pull request by DavieV**
Adding RgbToRgba functions with unit tests.

Also cleaning up the parameter validation code using variadic functions.

### CODE REVIEW

**Comment by ihhub** [comment]
Thanks for your efforts. There are multiple comment from my side. The main concern is why Normalize function fails in unit tests for Windows (check appveyor log).

**Comment by DavieV** [comment]
I don't currently have access to a Windows machine, but I'll take another look in a few days.

**Comment by ihhub** [comment]
Hi, @DavieV how things are going? Shall we make another review with suggested changes or you disagree with some of them?

**Comment by DavieV** [comment]
Hey, @ihhub . It seems I'm going to have to scrap most of the work I've done. I might look into redoing this in the future, but I don't really have the time right now.

**Comment by ihhub** [comment]
Hi, @DavieV . I've created a small issue addressing variadic templates which are done by you in this pull request. If you have a spare time I think you could change it (copy-paste from your code for a new pull request) as it's your initial code.

**Pull request closed without merging**
